services:
  - type: web
    name: Bitlyer
    env: node
    region: singapore
    plan: free
    branch: main
    startCommand: node .output/server/index.mjs
    buildCommand: npm install && npm run build
    healthCheckPath: /api/healthz
    envVars:
    - key: NITRO_PRESET
      value: render-com
    - key: NUXT_BITLY_REDIRECT_URL
      sync: false
    - key: NUXT_BITLY_CLIENT_ID
      sync: false
    - key: NUXT_BITLY_CLIENT_SECRET
      sync: false
    - key: NUXT_API_URL
      value: https://api-ssl.bitly.com